### ISSUE TITLE
No data from heating

### ISSUE THREAD

**Issue by dirk-schulz** [phha/vitowifi_esphome#5]
Hi, the nodemcu does not get any data from the viessmann heating system. Can someone explain me the correct cabeling. which parts for the LED and fototransistor have you used? anode, collector are the shot legs, correct? I would appreciate any support.

**Comment by phha** [comment]
You can find the wiring diagram and parts list here: https://github.com/openv/openv/wiki/Bauanleitung-ESP32-Adafruit-Feather-Huzzah32-and-Proto-Wing

**Comment by dirk-schulz** [comment]
Many thanks. That's exactly the wiring plan I'm using. With Vishay TSHA4401 and sfh309fa. But I get no data. As the sfh309fa is available in different versions (-2, - 4, -5) I was looking after a more concrete part list.
Do you have same examples where to order those parts?
And is the description of anode/collector correct to have the shortest leg? That's how I have connected Vishay TSHA4401 and sfh309fa. 
I'm struggling, if I have a hardware or software problem with my nodemcu v3?!
I would appreciate any support.

**Comment by dirk-schulz** [comment]
I also tried this wiring with the nodemcu https://github.com/openv/openv/wiki/Bauanleitung-ESP8266
But without gpio15 and without ch_pd, because having a nodemcu v3 here. Also tried it with a nodemcu v2 but also without any success.

**Comment by phha** [comment]
From here: https://github.com/openv/openv/wiki/Die-Optolink-Schnittstelle

> Dabei fungiert die linke LED (rot) zusätzlich zur Störungsanzeige als Infrarot-Empfänger, die rechte LED (grün) als Betriebsanzeige und Infrarotsender. Die Vitotronic sendet im Infrarotbereich mit einer Wellenlänge von 880nm, der Empfänger hat sein Empfindlichkeitsmaximum bei 860nm. Letzterer besitzt aber kein Infrarotfilter, weshalb der Empfänger auch auf Umgebungslicht (störend) reagiert.

It's been a long time since I built this and I no longer have access to the device so I'm not sure exactly which parts I used. But any two that fit the above specs (880nm for the receiver, 860nm for the sender) should do. You should be able to find one at any of the big electronics parts retailers.

Double check that you plugged it in correctly and shielding against ambient light helps too.

The long legs are indicated by a little bend in the wiring diagram.

If you are using a different SoC or connected the parts differently, you may have to adjust the pin numbers here: https://github.com/phha/vitowifi_esphome/blob/ff4a2efcc16d8ab9cb5d42a96ca849a5a5980585/custom_components/optolink/optolink.h#L39

**Comment by dirk-schulz** [comment]
Many thanks, issue could be solved by correct wiring. Anode of Vishay TSHA4401 (instead the 487) was on the long leg. So after turn it around it works.

**Comment by dirk-schulz** [comment]
Many thanks, issue could be solved by correct wiring. Anode of Vishay TSHA4401 (instead the 487) was on the long leg. So after turn it around it works.
